### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by Jamesli0123** [Not-IITian/Weakly-supervised-Deep-Functional-map#2]
hi, thank you for your great work, when I  run the code, the error appear, 
File "train_test.py", line 232, in load_subs
    input_data['target_shot'] = p_feat['VERT']             
KeyError: 'VERT'

 and I don't know how to deal with it. Is the datasets have problem? could you put your code in detail, looking for your early reply.

**Comment by bach-zouk** [comment]
Sure, this line basically loads the vertices from mesh. I should be able to fix the data in a day or so and will comment the code.

**Comment by Jamesli0123** [comment]
thank you. The problem has solved.
