### ISSUE TITLE
About Scape-remesh aligned Dataset Ground truth

### ISSUE THREAD

**Issue by Jamesli0123** [Not-IITian/Weakly-supervised-Deep-Functional-map#3]
Dear professor,
thanks for your great work. I want to know how to get the ground truth of the Scape remesh aligned, looking forward for your early reply. thanks again.

**Comment by bach-zouk** [comment]
Hi,

It is the same as scape remesh. Alignment does not change the vertices id.

**Comment by Jamesli0123** [comment]
I have got my matches on Scape dataset and now I want to calculate the geodetic error, but I don't know how to use the file of [.vts]. the file of .vts is the ground truth maps, but I don't know how to get maps around any pairs shapes, just like the map mesh060.off to mesh061 et al. Looking forward to your reply, thanks.
