### ISSUE TITLE
About how to ues scape ground truth

### ISSUE THREAD

**Issue by Jamesli0123** [Not-IITian/Weakly-supervised-Deep-Functional-map#4]
Dear professor，
I have got my matches on Scape dataset and now I want to calculate the geodetic error, but I don't know how to use the file of [.vts]. the file of .vts is the ground truth maps, but I don't know how to get maps around any pairs shapes, just like the map mesh060.off to mesh061 et al. Looking forward to your reply, thanks.

**Comment by bach-zouk** [comment]
Hi, this is some matlab code to evaluate the matches with vts files.
geo_dist_path = '../../../Data/GeoDistanceMatrix/';
Data_set ='FAUST_r';

if Data_set =='FAUST_r'   
    files_name1= 'tr_reg_0';
    range = 80:98;
    end_f= 99;
else
   % files_name= 'mesh0';
    range = 52:69;
    end_f=71;
end

 
 mat_path = [matches_path ]
for i = range  
    k1 = num2str(i);
    geo_name = '00'
    file1 = strcat(geo_name, k1);
    S1 = load([geo_dist_path, Data_set,'/', file1, '.mat']);
    
    target_off_fname = strcat(shapes_path, Data_set,'/OFF/', file1);
    
    [X, T] = readOff(target_off_fname);
   S1.surface.nv = size(X,1);   
    S1.VTS = load(strcat([shapes_path, Data_set,'/corres/', file1, '.vts']));   
    for j= i+1:end_f
        
        k2 = num2str(j);
        file2 = strcat(geo_name, k2);
        
        S2.VTS = load(strcat([shapes_path, Data_set, '/corres/', file2, '.vts']));
            S2.surface.nv = no_vertices_inS2;
        load(strcat(mat_path, '10000-/',files_name1, k1,'-' , files_name1, k2,'.mat')); 
        
        matches_0 = squeeze(matches)';
        map_to_S1 = matches_0(S2.VTS);

        ind_0 = sub2ind([S1.surface.nv, S1.surface.nv], S1.VTS, map_to_S1);             
         errs_0 = S1.Gamma(ind_0)/S1.SQRarea;   
        errs_tot_0 = [errs_tot_0 ; errs_0];
        
    end
   
 end
errs_vec = [mean(errs_tot_0)];
