### ISSUE TITLE
About Gamma Matrix.

### ISSUE THREAD

**Issue by Jamesli0123** [Not-IITian/Weakly-supervised-Deep-Functional-map#5]
Dear professor,
thanks for your reply, but new issue appear, I want to know what is gamma matrix, in your demo code, which is not present, so  I don't know what it means, and how to calculate it，looking forword  for your reply.thanks.

**Comment by bach-zouk** [comment]
Hi,

Gamma matrix is the geodesic matrix . you can them for faust and scape from this link: https://github.com/Not-IITian/SURFMNet-Object_oriented
